name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  app_ui:
    path: ../app_ui
  env:
    path: ../env
  image_picker_plus:
    path: ../image_picker_plus
  mocktail: ^1.0.4
  test: ^1.25.2
  very_good_analysis: ^6.0.0

dependencies:
  blurhash: ^1.1.1
  flutter:
    sdk: flutter
  flutter_image: ^4.1.11
  flutter_image_compress: ^2.3.0
  intl: ^0.19.0
  logger: ^2.4.0
  powersync: ^1.5.3
  uuid: ^4.5.1
  video_compress: ^3.1.3
