name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dev_dependencies:
  app_ui:
    path: ../app_ui
  env:
    path: ../env
  mocktail: ^1.0.4
  test: ^1.25.2
  very_good_analysis: ^6.0.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  logger: ^2.4.0
  powersync: ^1.5.3
