---
dependencies:
  animations: ^2.0.11
  api_repository:
    path: packages/api_repository
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  build_runner: ^2.4.13
  chats_repository:
    path: packages/chats_repository
  collection: ^1.18.0
  con_blocks:
    path: packages/con_blocks
  conexion_blocks_ui:
    path: packages/conexion_blocks_ui
  database_client:
    path: packages/database_client
  env:
    path: packages/env
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  firebase_remote_config_repository:
    path: packages/firebase_remote_config_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  form_fields:
    path: packages/form_fields
  get_it: ^8.0.0
  go_router: ^14.3.0
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.5
  image_picker_plus:
    path: packages/image_picker_plus
  intl: ^0.19.0
  inview_notifier_list: ^3.0.0
  json_annotation: ^4.9.0
  json_serializer: ^0.2.0
  lottie: ^3.1.3
  meta: ^1.15.0
  path: '>=1.8.3 <=1.9.0'
  path_provider: ^2.1.4
  posts_repository:
    path: packages/posts_repository
  powersync: ^1.7.0
  powersync_repository:
    path: packages/powersync_repository
  scrollable_positioned_list: ^0.3.8
  shared:
    path: packages/shared
  slang: ^4.2.1
  slang_build_runner: ^4.1.0
  slang_flutter: ^4.1.0
  sliver_tools: ^0.2.12
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  supabase_flutter: ^2.8.1
  timeago: ^3.7.0
  token_storage:
    path: packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository
  video_player_platform_interface_extra: ^5.0.1+1
description: A Very Good Project created by Very Good CLI.
dev_dependencies:
  bloc_test: ^9.1.7
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
environment:
  sdk: ^3.4.0
flutter:
  generate: true
  uses-material-design: true
name: conexion
publish_to: none
version: 1.0.0+1
