name: conexion
description: DACN Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  api_repository: 
    path: packages/api_repository
  bloc: ^8.1.4
  envied: ^0.5.4+1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6

  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
