name: conexion
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  api_repository:
    path: packages/api_repository
  bloc: ^8.1.4
  env:
    path: packages/env
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.0
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  path: ">=1.8.3 <=1.9.0"
  powersync: ^1.8.7
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared
  supabase_flutter: ^2.6.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
