name: conexion
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  animations: ^2.0.11
  api_repository:
    path: packages/api_repository
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.4
  conexion_blocks_ui:
    path: packages/conexion_blocks_ui
  database_client:
    path: packages/database_client
  env:
    path: packages/env
  equatable: ^2.0.5
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  form_fields:
    path: packages/form_fields
  get_it: ^8.0.0
  go_router: ^14.3.0
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  path: ">=1.8.3 <=1.9.0"
  path_provider: ^2.1.4
  posts_repository:
    path: packages/posts_repository
  powersync: ^1.7.0
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared
  image_picker_plus:
    path: packages/image_picker_plus
  sliver_tools: ^0.2.12
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  supabase_flutter: ^2.6.0
  token_storage:
    path: packages/authentication_client/token_storage
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  meta: ^1.15.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
