// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnfBMn1qHMzoI9DZBTQGLQQEd3ZzcFdy8',
    appId: '1:804958021896:web:474e20e21482d4e32d64bd',
    messagingSenderId: '804958021896',
    projectId: 'dacn-dev',
    authDomain: 'dacn-dev.firebaseapp.com',
    storageBucket: 'dacn-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_SeZ63O79xVhxoYajpIIqTI2AmjJmbjk',
    appId: '1:804958021896:android:afad04cbf32adce12d64bd',
    messagingSenderId: '804958021896',
    projectId: 'dacn-dev',
    storageBucket: 'dacn-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZovxakNjm60xSaBw83I72VOoESy5Onm0',
    appId: '1:804958021896:ios:e92fcc03e08dbe572d64bd',
    messagingSenderId: '804958021896',
    projectId: 'dacn-dev',
    storageBucket: 'dacn-dev.appspot.com',
    androidClientId: '804958021896-tg426a48e6m10avrb2hlf820l97pqaog.apps.googleusercontent.com',
    iosClientId: '804958021896-va88cr615h9qqel81hlm6hoiigda453e.apps.googleusercontent.com',
    iosBundleId: 'com.dacn.conexion.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZovxakNjm60xSaBw83I72VOoESy5Onm0',
    appId: '1:804958021896:ios:e92fcc03e08dbe572d64bd',
    messagingSenderId: '804958021896',
    projectId: 'dacn-dev',
    storageBucket: 'dacn-dev.appspot.com',
    androidClientId: '804958021896-tg426a48e6m10avrb2hlf820l97pqaog.apps.googleusercontent.com',
    iosClientId: '804958021896-va88cr615h9qqel81hlm6hoiigda453e.apps.googleusercontent.com',
    iosBundleId: 'com.dacn.conexion.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnfBMn1qHMzoI9DZBTQGLQQEd3ZzcFdy8',
    appId: '1:804958021896:web:f4595ff0a75ea0672d64bd',
    messagingSenderId: '804958021896',
    projectId: 'dacn-dev',
    authDomain: 'dacn-dev.firebaseapp.com',
    storageBucket: 'dacn-dev.appspot.com',
  );
}
