// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPMAqBgvQVmnByhJdTBRp-ViNU6XsqjkQ',
    appId: '1:864221569797:web:7c38500b0ffa380b02cd6c',
    messagingSenderId: '864221569797',
    projectId: 'dacn-staging',
    authDomain: 'dacn-staging.firebaseapp.com',
    storageBucket: 'dacn-staging.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtO76Wp76xHZ-13-js0N3ad0YG7QqltBo',
    appId: '1:864221569797:android:512d98918a3dd1c402cd6c',
    messagingSenderId: '864221569797',
    projectId: 'dacn-staging',
    storageBucket: 'dacn-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZgpQ5Isio2DElXZwXdZVjBYsq_Xpb-nI',
    appId: '1:864221569797:ios:36887ce5e35ea18e02cd6c',
    messagingSenderId: '864221569797',
    projectId: 'dacn-staging',
    storageBucket: 'dacn-staging.appspot.com',
    androidClientId: '864221569797-jsfo30hufpu9k93fpi1i25a56kj55se0.apps.googleusercontent.com',
    iosClientId: '864221569797-ni3ukv9m14or8v63qlp1lq73p3a1c7ec.apps.googleusercontent.com',
    iosBundleId: 'com.dacn.conexion.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZgpQ5Isio2DElXZwXdZVjBYsq_Xpb-nI',
    appId: '1:864221569797:ios:36887ce5e35ea18e02cd6c',
    messagingSenderId: '864221569797',
    projectId: 'dacn-staging',
    storageBucket: 'dacn-staging.appspot.com',
    androidClientId: '864221569797-jsfo30hufpu9k93fpi1i25a56kj55se0.apps.googleusercontent.com',
    iosClientId: '864221569797-ni3ukv9m14or8v63qlp1lq73p3a1c7ec.apps.googleusercontent.com',
    iosBundleId: 'com.dacn.conexion.staging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPMAqBgvQVmnByhJdTBRp-ViNU6XsqjkQ',
    appId: '1:864221569797:web:7822764c2fe3566b02cd6c',
    messagingSenderId: '864221569797',
    projectId: 'dacn-staging',
    authDomain: 'dacn-staging.firebaseapp.com',
    storageBucket: 'dacn-staging.appspot.com',
  );
}
