name: conexion_blocks_ui
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_ui:
    path: ../app_ui
  cached_memory_image: ^1.5.0
  cached_network: ^2.1.0
  cached_network_image: ^3.3.1
  con_blocks:
    path: ../con_blocks
  flutter:
    sdk: flutter
  powersync_repository:
    path: ../powersync_repository
  shared:
    path: ../shared
  user_repository:
    path: ../user_repository

  shimmer: any
  inview_notifier_list: ^3.0.0
  octo_image: ^2.1.0
  flutter_blurhash: ^0.8.2
  smooth_video_progress: ^0.0.4
  video_player: ^2.9.2
  visibility_detector: ^0.4.0+2
  flutter_animate: ^4.5.0
  sprung: ^3.0.1
  carousel_slider: ^5.0.0
  avatar_stack: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
