name: stories_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies: 
  collection: ^1.18.0
  database_client:
    path: ../database_client
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  shared:
    path: ../shared
  storage:
    path: ../storage/storage
  user_repository:
    path: ../user_repository
    
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
